# Generated by Django 3.2.4 on 2021-06-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('social', '0003_auto_20210607_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='member',
            field=models.ManyToManyField(related_name='like', to='member.Member'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='article',
        ),
        migrations.AddField(
            model_name='like',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='social.article'),
        ),
    ]
