# Generated by Django 3.2.4 on 2021-06-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('social', '0004_auto_20210608_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='member',
            field=models.ManyToManyField(related_name='liked_article', to='member.Member'),
        ),
    ]
